### ISSUE TITLE
计算机领域的三个重要思想：抽象，分层和高阶

### ISSUE THREAD

**Issue by qiwihui** [qiwihui/pocket_readings#1050]
&#26152;&#26202;&#30475;&#20102;&#28857;&#27604;&#36739;&#26377;&#24847;&#24605;&#30340;&#19996;&#35199;&#65292;&#20110;&#26159;&#20915;&#23450;&#20889;&#19968;&#31687;&#25991;&#31456;&#31616;&#21333;&#35762;&#19968;&#19979;&#12290;<br>
<br>
Tags:<br>
<br>
via Pocket https://ift.tt/3uTZfMJ original site<br>
<br>
March 19, 2021 at 10:58AM

**Comment by zzz6519003** [comment]
这个actions用的啥魔法
